dist: xenial

services:
  - docker

install:
  - docker build -t ganeti --build-arg uid=$(id -u) --file Dockerfile.stretch .

script:
  - docker run -v $(pwd):/build ganeti sh -c "./autogen.sh && ./configure --enable-haskell-tests && make"
  - docker run -v $(pwd):/build ganeti make py-tests
  - docker run -v $(pwd):/build ganeti make hs-tests
