---
name: Build & Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: autogen
        uses: docker://ganeti/ci:buster-py3
        with:
          args: ./autogen.sh

      - name: configure
        uses: docker://ganeti/ci:buster-py3
        with:
          args: ./configure --prefix=/opt/ganeti --enable-symlinks --enable-haskell-tests

      - name: Build
        uses: docker://ganeti/ci:buster-py3
        with:
          args: make -j 2

      #- name: Python tests
      #  uses: docker://ganeti/ci:buster-py3
      #  with:
      #    args: make py-tests

      #- name: Haskell tests
      #  uses: docker://ganeti/ci:buster-py3
      #  with:
      #    args: make -j 2 hs-tests

      - name: Install
        uses: docker://ganeti/ci:buster-py3
        with:
          args: sh -c "make install && tar -C /opt -cvzf ganeti.tar.gz ganeti"

      - name: Upload tarball
        uses: actions/upload-artifact@v1
        with:
          name: tarballs
          path: ganeti.tar.gz

  qa:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Download tarball
        uses: actions/download-artifact@v1
        with:
          name: tarballs

      - name: Run vcluster QA
        uses: docker://ganeti/ci:buster-py3
        with:
          args: sh -c "tar -C /opt -xvf tarballs/ganeti.tar.gz && .github/workflows/vcluster-qa"
