---
name: vcluster QA
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: autogen
        uses: docker://ganeti/ci:buster-py3
        with:
          args: ./autogen.sh

      - name: configure
        uses: docker://ganeti/ci:buster-py3
        with:
          args: ./configure --prefix=/opt/ganeti --enable-symlinks

      - name: Build
        uses: docker://ganeti/ci:buster-py3
        with:
          args: make -j 2

      - name: Install & run QA
        uses: docker://ganeti/ci:buster-py3
        with:
          args: sh -c "make install && .github/workflows/vcluster-qa"
